# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-02 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='public',
            field=models.BooleanField(default=0),
        ),
    ]
